<?php require_once("template/header.phtml"); ?>
<!-- TODO: This styling is a mess, just a proof of concept -->

<div class="container">
    <div class="row">
        <h1 class="col-lg-12"><?php echo $view->user->getFullname() ?></h1>
        <?php
            if (isset($_SESSION['loggedIn']))
            { ?>
                <img class=" img-circle" alt="user avatar" src=<?php echo "images/".$view->user->getAvatar()?>>
                <h3 class="col-lg-12"><?php echo $view->user->getUsername() ?></h3>
              <?php
            }
            else
            { ?>
                <h3 class="col-lg-12">Please log in to view user details</h3>
              <?php
            }
        ?>
        <h3 class="col-lg-12">Number of Posts Made: <?php echo $view->postCount ?></h3>
        <h3 class="col-lg-12">Number of Replies: <?php echo $view->replyCount ?></h3>
    </div>
    <ul class="list-group">
        <h2></h2>
        <?php
        foreach ($view->userPosts as $post) { ?>
            <li class="list-group-item list-element">
                <h3> <a href="fullpost.php?id=<?php echo $post->getId() ?>"> <?php echo $post->getTitle() ?></a></h3>
                <small> <a href="account.php?id=<?php echo $post->getPosterId()?>"><?php echo $post->getPosterFullName()?></a></small>
                <p><?php echo $post->getContent() ?></p>
                <p>Number Of Comments: <?php echo $post->getReplyCount() ?></p>
            </li>
        <?php } ?>
    </ul>
</div>
<?php require_once("template/footer.phtml"); ?>
