<?php require_once ("template/header.phtml"); ?>
<h1 class="text-center display-4">Categories</h1>
<ul class="list-group">
<?php
foreach ($view->categories as $category)
{
 ?>
    <li class="list-group-item list-element">
        <div class="container">
            <a href="posts.php?categoryID=<?php echo $category->getCategoryID()?>&page=1&limit=25&sort=1">
                <h3 class="list-group-item-heading"><?php echo $category->getCategoryName()?></h3>
            </a>

            <p>Current post count: <?php echo $category->getCategoryPostCount()?></p>
        </div>
    </li>
 <?php
}
?>
</ul>
<?php require_once ("template/footer.phtml"); ?>
