<?php require_once ("template/header.phtml"); ?>
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<div class="container">
    <div class="container">
        <h1 class="text-center display-4">Create New Account</h1>
        <form class="form-horizontal" enctype="multipart/form-data" action="createuser.php" method="POST">
            <div class="form-group">
                <label class="label" for="username">Username</label>
                <input class="form-control" type="text" id="username" name="username" placeholder="Arya@Stark.com" required>
            </div>
            <div class="form-group">
                <label class="label" for="password">Password</label>
                <input class="form-control" type="password" id="password" name="password" required>
            </div>

            <div class="form-group">
                <label class="label" for="firstname">Firstname</label>
                <input class="form-control" type="text" id="firstname" name="firstname" placeholder="Arya" required>
            </div>

            <div class="form-group">
                <label class="label" for="lastname">Lastname</label>
                <input class="form-control" type="text" id="lastname" name="lastname" placeholder="Stark" required>
            </div>

            <div class="form-group">
                <input type="file" name="user_avatar" class="form-control-file">
            </div>

            <div class="text-xs-centre">
                <div class="g-recaptcha" data-sitekey="6Lc0psUUAAAAAHbF17kNtEPOcTY_c90mgAHZjhWp"></div>
            </div>

            <div class="form-group">
                <button class="form-control btn btn-outline-primary" type="submit" name="submit">
                    Create Account
                </button>
            </div>
        </form>
    </div>
</div>
<?php require_once ("template/footer.phtml") ?>
