<?php require_once("template/header.phtml"); ?>

<?php
$mainPost = $view->mainPost;
$loggedIn = isset($_SESSION['loggedIn']);
?>

<?php
    if (isset($view->message))
    {
        require_once ("template/info.phtml");
    }

    if (isset($view->error))
    {
        require_once ("template/error.phtml");
    }
?>
<div class="container">
<div class="container post-container">

    <ul class="list-group">

        <li class="list-group-item list-element">

            <div class="row">

                <div class="col-sm-12">
                    <?php if ($loggedIn)
                    {
                        if ($view->isOnWatchlist)
                        { ?>
                            <a href="unsubscribe.php?id=<?php echo $mainPost->getId()?>">
                                <i class='fas fa-bookmark icon-lg'></i>
                            </a>
                            <?php
                        }
                        else
                        { ?>
                            <a href="subscribe.php?id=<?php echo $mainPost->getId()?>">
                                <i class='far fa-bookmark icon-lg'></i>
                            </a>
                            <?php
                        }

                    }
                    ?>
                    <h1 class="text-center">
                        <?php echo $mainPost->getTitle()?>
                    </h1>

                </div>

                <div class="col-sm-12">

                    <h4 class="text-muted text-center">
                        <a href="myaccount.php?id=<?php echo $mainPost->getPosterID() ?>">
                            <?php echo $mainPost->getPosterFullName() ?>
                        </a>
                    </h4>

                </div>

                <div class="col-sm-12">
                    <p class="text-center lead">
                        <?php echo $mainPost->getContent() ?>
                    </p>
                </div>

                <?php if(isset($_SESSION['loggedIn']))
                    {
                        if ($mainPost->getImage())
                            { ?>


                                    <img class="col-sm-4 mx-auto" src="images/<?php echo $mainPost->getImage() ?>">

                             <?php
                            } ?>
                        <div class="col-sm-12">
                            <button class="btn btn-outline-primary reply-button" data-toggle="modal" data-target="#replyModal">Reply</button>
                        </div>

                        <div class="modal fade" tabindex="-1" id="replyModal" role="dialog">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">Reply</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>

                                    <form action="createReply.php?id=<?php echo $mainPost->getId()?>&&categoryID=<?php echo $mainPost->getCategoryID() ?>" method="post">
                                        <div class="modal-body">
                                            <div class="form-group">
                                                <label for="title">Title</label>
                                                <input type="text" id="title" class="form-control" name="title">
                                            </div>
                                            <div class="form-group">
                                                <label for="comment">Comment</label>
                                                <textarea id="comment" class="form-control" name="content"></textarea>
                                            </div>

                                            <div class="text-xs-centre">
                                                <div id="reCaptcha" class="g-recaptcha" data-sitekey="6Lc0psUUAAAAAHbF17kNtEPOcTY_c90mgAHZjhWp"></div>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close
                                            </button>
                                            <button type="submit" name="submit" class="btn btn-outline-primary">
                                                Post Reply
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    <?php } ?>

            </div>
        </li>
    </ul>
</div>

    <div class="container post-container">

        <!-- Reply -->
        <ul class="list-group">
            <?php
            foreach ($view->replies as $reply)
            {?>
                <li class="list-group-item list-element">

                    <div class="row">

                        <div class="col-sm-12">
                            <h2 class=text-center>
                                <?php echo $reply->getTitle() ?>
                            </h2>
                        </div>

                        <div class="col-sm-12">

                            <h4 class="text-muted text-center">

                                <a href="account.php?id=<?php echo $reply->getPosterID() ?>">
                                    <?php echo $reply->getPosterFullname() ?>
                                </a>

                            </h4>
                        </div>

                        <div class="col-sm-12">
                            <p class="lead text-center">
                                <?php echo $reply->getContent() ?>
                            </p>
                        </div>

                    </div>

                </li>
            <?php } ?>
        </ul>
    </div>

</div>
<?php require_once ("template/footer.phtml") ?>