<?php require_once("template/header.phtml"); ?>

<?php $mainPost = $view->mainPost ?>

<div class="container post-container">

    <ul class="list-group">

        <li class="list-group-item">

            <div class="row">

                <div class="col-sm-12">

                    <h3 class="text-center display-4">
                        <?php echo $mainPost->getTitle()?>
                    </h3>

                </div>

                <div class="col-sm-12">

                    <h3 class="text-muted text-center">
                        <a href="myaccount.php?id=<?php echo $mainPost->getPosterID() ?>">
                            <?php echo $mainPost->getPosterUsername() ?>
                        </a>
                    </h3>

                </div>

                <div class="container text-center">

                    <p>
                      <?php echo $mainPost->getContent() ?>
                    </p>

                </div>

            </div>

        </li>

        <!-- Reply -->
        <ul class="list-group">
            <?php
            foreach ($view->replies as $reply)
            {?>
                <li class="list-group-item reply">

                    <div class="row">

                        <div class="col-sm-12">
                            <h3>
                                <?php echo $reply->getTitle() ?>
                            </h3>
                        </div>

                        <div class="col-sm-12">

                            <small class="text-muted">

                                <a href="myaccount.php?id=<?php echo $reply->getPosterID() ?>">
                                    <?php echo $reply->getPosterUsername() ?>
                                </a>

                            </small>
                        </div>

                        <div class="col-sm-12">
                            <p>
                                <?php echo $reply->getContent() ?>
                            </p>
                        </div>



                    </div>

                </li>
            <?php } ?>
        </ul>

    </ul>

</div>
<?php require_once ("template/footer.phtml") ?>