<?php require('template/header.phtml') ?>
<?php
if (isset($_SESSION['loggedIn'])) {
    // User is logged in and authenticated
    $userFirstName = $_SESSION['username'];
    echo "<h1>Welcome" . $userFirstName .
        "<a href='logout.php'>Logout</a>";
} else {
    ?>
    <div class="row">
        <button class='btn btn-primary' data-toggle='modal' data-target='#loginModal'>Login</button>
    </div>

    <div class="modal fade" tabindex="-1" role="dialog" id="loginModal">
        <form action="login.php" method="post">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Login</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <!-- Login Form -->

                        <!-- Username -->
                        <div class="form-group">
                            <label class="label" for="username">
                                Username
                            </label>
                            <input class="form-control" id="username" type="text" name="username"
                                   placeholder="jon@snow.com">
                        </div>
                        <div class="form-group">
                            <label class="label" for="password">
                                Password
                            </label>
                            <input class="form-control" id="password" type="password" name="password">
                        </div>

                        <div class="form-group">
                            <a href="createaccount.php">Not got an account? Create one here</a>
                        </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <input class="btn btn-primary" type="submit" name="submit" value="Login">
                </div>
            </div>
        </div>
        </form>
        </div>

    <?php
}
?>
<?php require('template/footer.phtml') ?>
