<?php require('template/header.phtml') ?>
<?php
if (isset($_SESSION['loggedIn'])) {
    // User is logged in and authenticated
    $userFirstName = $_SESSION['username'];
    echo "<h1>Welcome" . $userFirstName . "</h1>";
    echo "<img src=" . 'images/'.$view->user->getAvatar() . ">";
} ?>

<?php if (isset($view->error))
    { ?>
        <div class="alert show fade  alert-danger text-center" role="alert">
            <?php echo $view->error ?>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
      <?php
    } ?>
<?php require('template/footer.phtml') ?>
