<?php require_once ("template/header.phtml"); ?>

<h3>Recieved Messages</h3>
<ul class="list-group">
    <?php
        foreach ($view->recievedMessages as $message)
        { ?>
            <li class="list-group-item">
                <h3>From: <?php echo $message->getMessageSenderUsername() ?></h3>
                <p><?php echo $message->getMessageContent() ?></p>
            </li>
          <?php
        }
    ?>
</ul>

<hr>

<h3>Sent Messages</h3>
<ul class="list-group">
    <?php
        foreach ($view->sentMessages as $message)
        { ?>
            <li class="list-group-item">
                <h3>To: <?php echo $message->getMessageRecipientUsername() ?></h3>
                <p><?php echo $message->getMessageContent() ?></p>
            </li>
          <?php
        }
    ?>
</ul>

<?php require_once ("template/footer.phtml"); ?>
