<?php require_once ("template/header.phtml"); ?>

<div class="container">
  <div class="container">
    <ul id="msg" class="list-group">
    <ul>
  </div>
</div>
<script>
    function sendMessage() {
        var xhr = new XMLHttpRequest();
        xhr.open("POST", "sendmessage.php", true);
        xhr.onreadystatechange = function() {
            if (this.readyState == 4 && this.status == 200) {
                console.log(this.responseText)
            }
        }
        xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
        let recipientID = "67";
        let content = "TEST MESSAGE 2";
        xhr.send(`id=${recipientID}&content=${content}`);
    }
function createLst() {
        const id = "<?php echo $_SESSION['id'] ?>";
        const lst = document.getElementById('msg');
    // Make a call to loadInbox.php and retrieve a list of "conversations" ordered by Newest -> Oldest.
    fetch(`getConversations.php?id=${id}`).then((result) => {
        return result.text()
    }).then((data) => {
        console.log(data)
        let res = JSON.parse(data);
        res.forEach(conversation => lst.append(new Conversation(conversation.id, conversation.username, null).build()))
    }).catch((error) => {
        console.log(error)
    })
}
   
    class Conversation {
      constructor(id, author, avatar) {
        this.id = id;
        this.author = author
        this.avatar = avatar
      }

      build() {
        let list = document.createElement("li");
        let div = document.createElement("div");
        let name = document.createElement("a");
        name.innerHTML = this.author;
        list.className = "list-group-item list-element col-sm-12";
        name.className = "list-group-item-heading text-center";
        name.href = `conversation.php?id=${this.id}`
        list.append(div)
        div.append(name)

        return list
      }
    }

window.addEventListener("load", createLst);
</script>
<?php require_once ("template/footer.phtml"); ?>
  