<?php require_once("template/header.phtml"); ?>
<!-- TODO: This styling is a mess, just a proof of concept -->
<!-- ON some users (possibly just default ones) the user avatar doesnt load? -->
<div class="container">
    <div class="row">
        <img class=" img-circle" src=<?php echo "images/".$view->user->getAvatar() ?>>
        <h1 class="col-lg-12"><?php echo $view->user->getUsername() ?></h1>
        <h3 class="col-lg-12">Number of Posts Made: <?php echo $view->postCount ?></h3>
        <h3 class="col-lg-12">Number of Replies: <?php echo $view->replyCount ?></h3>
    </div>
    <ul class="list-group">
        <h2></h2>
        <?php
        foreach ($view->userPosts as $post) { ?>
            <li class="list-group-item">
                <h3> <a href="fullpost.php?id=<?php echo $post->getId() ?>"> <?php echo $post->getTitle() ?></a></h3>
                <small> <a href="myaccount.php?id=<?php echo $post->getPosterId()?>"><?php echo $post->getPosterUsername()?></a></small>
                <p><?php echo $post->getContent() ?></p>
            </li>
        <?php } ?>
    </ul>
</div>
<?php require_once("template/footer.phtml"); ?>
