<script type="text/javascript" src="../js/scrollingPosts.js"></script>
<?php require_once("template/header.phtml"); ?>

<?php
if (isset($view->error))
{
    require_once ("template/error.phtml");
}

if (isset($view->message))
{
    require_once ("template/info.phtml");
}
?>
<div class="container">
    <h1  id="pageHeading" class="text-center display-4 col-sm-12"><?php echo $view->categoryName ?></h1>
    <?php require_once("template/searchbar.phtml"); ?>

    <?php if(isset($_SESSION['loggedIn']))
        {
            require_once ("template/newpost.phtml");
        }
        ?>
    <ul id='postList' class="list-group">
        <?php
        foreach ($view->posts as $post) { ?>
            <li class="list-group-item list-element col-sm-12">
                <div>
                    <a href="fullpost.php?id=<?php echo $post->getId() ?>">
                        <h1 class="list-group-item-heading text-center"><?php echo $post->getTitle() ?></h1>
                    </a>
                    <a href="account.php?id=<?php echo $post->getPosterID()?>">
                        <h4 class="text-muted text-center"><?php echo $post->getPosterFullName() ?></h4>
                    </a>
                    <h4 class="lead text-center"><?php echo $post->getContent() ?></h4>
                    <h5 class="text-center">Number of comments: <?php echo $post->getReplyCount() ?></h5>
                </div>
            </li>
        <?php }
        ?>
    </ul>
</div>
<script>
    let page = Number(<?php echo $view->currentPage?>);
    let pageCount = Number(<?php echo $view->pageCount?>);
    let categoryID = Number(<?php echo $view->currentCategory?>);
    let limit = Number(<?php echo $view->limit?>);
    let dateOrder = Number(<?php echo $view->dateOrder?>);
    let title = "<?php echo $view->title?>";
    let comment = <?php echo $view->commentOrder?>;

    document.addEventListener('scroll', () => {
        if (document.body.scrollHeight === (document.body.scrollTop + window.innerHeight)) {
            if (page <= pageCount) {
                getNextPosts(categoryID, page, limit, dateOrder, comment, title);
                page++
            }
        }
    });
</script>
<?php require_once("template/footer.phtml"); ?>
