<?php require_once("template/header.phtml"); ?>

<?php
if (isset($view->error))
{
    require_once ("template/error.phtml");
}

if (isset($view->message))
{
    require_once ("template/info.phtml");
}
?>

<h1 class="text-center display-4"><?php echo $view->categoryName ?></h1>
<?php require_once("template/searchbar.phtml"); ?>

<?php if(isset($_SESSION['loggedIn']))
    {
        require_once ("template/newpost.phtml");
    }
    ?>
<ul class="list-group">
    <?php
    foreach ($view->posts as $post) { ?>
        <li class="list-group-item list-element">
            <div>
                <a href="fullpost.php?id=<?php echo $post->getId() ?>">
                    <h3 class="list-group-item-heading"><?php echo $post->getTitle() ?></h3>
                </a>
                <a href="account.php?id=<?php echo $post->getPosterID()?>">
                    <small><?php echo $post->getPosterFullName() ?></small>
                </a>
                <p><?php echo $post->getContent() ?></p>
                <p>Number of comments: <?php echo $post->getReplyCount() ?></p>
            </div>
        </li>
    <?php }
    ?>
</ul>

<?php require_once ("template/pagination.phtml") ?>

<?php require_once("template/footer.phtml"); ?>
