<script>
    let page = Number(<?php echo $view->currentPage?>);
    let pageCount = Number(<?php echo $view->pageCount?>);
    let categoryID = Number(<?php echo $view->currentCategory?>);
    let limit = Number(<?php echo $view->limit?>);
    let dateOrder = Number(<?php echo $view->dateOrder?>);
    let title = "<?php echo $view->title?>";
    let comment = <?php echo $view->commentOrder?>;

    function getNextPosts() {
        page++;
        fetch(`getNextPosts.php?categoryID=${categoryID}&page=${page}&limit=${limit}&date=${dateOrder}&comment=${comment}&title=${title}`).then((result) => {
            return result.text()
        }).then((data) => {
            const posts = JSON.parse(data);
            let postList = document.getElementById('postList');
            if (posts.length === 0) {
                let alert = document.createElement("div");
                alert.setAttribute("role", "alert");
                alert.className = "alert alert-danger";
                alert.innerHTML = "Theres nothing more UwU";
                postList.appendChild(alert)
            }
                posts.forEach((post) => {
                    postList.appendChild(new Post(post._id, post._title, post._posterID, post._posterFullName, post._content, post._replyCount).build());
                });

        }).catch((error) => {
            console.error(error)
        })
    }

    document.addEventListener('scroll', function (event) {
        if (document.body.scrollHeight === (document.body.scrollTop + window.innerHeight)) {
            if (page <= pageCount) {
                getNextPosts();
            }
        }
    });

    class Post {
        constructor(id, title, posterID, posterFullName, content, replyCount) {
            this.id = id;
            this.title = title;
            this.posterID = posterID;
            this.posterFullName = posterFullName;
            this.content = content;
            this.replyCount = replyCount;
        }

        build() {
            let list = document.createElement("li");
            let div = document.createElement("div");
            let postLink = document.createElement("a");
            let title = document.createElement("h1");
            let accountLink = document.createElement("a");
            let posterName = document.createElement("h4");
            let content = document.createElement("h4");
            let commentCount = document.createElement("h5");



            list.className = "list-group-item list-element col-sm-12";
            title.className = "list-group-item-heading text-center";
            posterName.className = "text-muted text-center";
            content .className = "lead text-center";
            commentCount.className = "text-center";

            postLink.href = `fullpost.php?id=${this.id}`;
            accountLink.href = `account.php?id=${this.posterID}`;
            title.innerHTML = this.title;
            posterName.innerHTML = this.posterFullName;
            content.innerHTML = this.content;
            commentCount.innerHTML = `Number of Comments: ${this.replyCount}`;

            list.append(div);
            div.appendChild(postLink);
            postLink.appendChild(title);
            div.appendChild(accountLink);
            accountLink.appendChild(posterName);
            div.appendChild(content);
            div.appendChild(commentCount);

            return list;
        }
    }
</script>

<?php require_once("template/header.phtml"); ?>

<?php
if (isset($view->error))
{
    require_once ("template/error.phtml");
}

if (isset($view->message))
{
    require_once ("template/info.phtml");
}
?>
<div class="container">
    <h1  id="pageHeading" class="text-center display-4 col-sm-12" onclick="getNextPosts()"><?php echo $view->categoryName ?></h1>
    <?php require_once("template/searchbar.phtml"); ?>

    <?php if(isset($_SESSION['loggedIn']))
        {
            require_once ("template/newpost.phtml");
        }
        ?>
    <ul id='postList' class="list-group">
        <?php
        foreach ($view->posts as $post) { ?>
            <li class="list-group-item list-element col-sm-12">
                <div>
                    <a href="fullpost.php?id=<?php echo $post->getId() ?>">
                        <h1 class="list-group-item-heading text-center"><?php echo $post->getTitle() ?></h1>
                    </a>
                    <a href="account.php?id=<?php echo $post->getPosterID()?>">
                        <h4 class="text-muted text-center"><?php echo $post->getPosterFullName() ?></h4>
                    </a>
                    <h4 class="lead text-center"><?php echo $post->getContent() ?></h4>
                    <h5 class="text-center">Number of comments: <?php echo $post->getReplyCount() ?></h5>
                </div>
            </li>
        <?php }
        ?>
    </ul>
</div>

<?php require_once("template/footer.phtml"); ?>
