<?php require_once ("template/header.phtml"); ?>
<h3 class="display-4 text-center">Watchlist</h3>
<ul class="list-group">
<?php
 foreach ($view->userWatchlist as $post)
 { ?>
     <li class="list-group-item list-element">
         <a href="fullpost.php?id=<?php echo $post->getId()?>">
             <h3 class="list-group-item-heading"><?php echo $post->getTitle() ?>
             </h3>
         </a>
         <a href="myaccount.php?id=<?php echo $post->getPosterID()?>">
             <small><?php echo $post->getPosterFullname() ?></small>
         </a>
         <a href="unsubscribe.php?id=<?php echo $post->getId()?>&from=Watchlist">Unsubscribe</a>
         <p><?php echo $post->getContent() ?></p>
         <p>Number of Comments: <?php echo $post->getReplyCount() ?></p>
     </li>

 <?php }
?>
</ul>
<?php require_once ("template/footer.phtml"); ?>
