<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <!--  Bootstrap CDN  -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!--  Font Awesome  -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <!--  Custom Styling  -->
    <link href="/css/my-style.css" rel="stylesheet">

    <title><?php echo $view->pageTitle; ?></title>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
</head>

<body role="document">
<nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand" href="#">Forum</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="index.php">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="categories.php">Categories</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false">
                    Account
                </a>
                <div class="dropdown-menu">
                    <?php
                    if (isset($_SESSION['username'])) {
                        $id = $_SESSION['id'];
                        echo "<a class='dropdown-item' href='myaccount.php?id=$id'>My Account</a>";
                        echo "<a class='dropdown-item' href='watchlist.php?id=$id'>My Watchlist</a>";
                        echo "<a class='dropdown-item' href='logout.php'>Logout</a>";
                    } else {
                        echo "<a class=\"dropdown-item\" href=\"#\" data-toggle=\"modal\" role=\"button\" data-target=\"#loginModal\">
                        Login / Create Account
                        </a>";
                    }
                    ?>
                </div>
            </li>
        </ul>
    </div>
</nav>

<?php
if (!isset($_SESSION['username'])) {
    ?>
    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalTitle"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="loginModalTitle">Login</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form class="form" action="login.php" method="POST">
                    <div class="modal-body">
                        <div class="container-fluid">
                            <div class="form-group row text-center">
                                <label class="control-label col-sm-12 col-md-4" for="username">Username</label>
                                <input class="form-control col-sm-12 col-md-8" type="text" id="username" name="username"
                                       placeholder="Jon@Snow.com">
                            </div>
                            <div class="form-group row text-center">
                                <label class="control-label col-sm-12 col-md-4" for="password">Password</label>
                                <input class="form-control col-sm-12 col-md-8" type="password" id="password"
                                       name="password">
                            </div>
                            <div class="text-xs-centre">
                            <div class="g-recaptcha" data-sitekey="6Lc0psUUAAAAAHbF17kNtEPOcTY_c90mgAHZjhWp"></div>
                            </div>
    
                            <div class="form-group text-center">
                                <a href="createaccount.php">Not got an account? Create one here!</a>
                            </div>

                        </div>
                    </div>
                    <!-- TODO: Change buttons so sm->md they stack and md->* they are side by side 11:57AM 29/11/2019 -->
                    <div class="modal-footer">

                        <button type="button" class="btn btn-secondary" data-dismiss="modal">
                            Close
                        </button>
                        <input class="btn btn-primary" type="submit" name="submit" value="submit">

                    </div>
                </form>
            </div>
        </div>
    </div>
    <?php
}
?>
<div class="container">



