
    <button type="button" class="btn btn-outline-primary btn-block" data-toggle="modal"
            data-target="#createPost">
        New Post
    </button>

    <div>
        <div class="modal fade" tabindex="-1" id="createPost"
             role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Create New Post</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <form enctype="multipart/form-data" action="createpost.php?categoryID=<?php echo $_GET['categoryID']?>" method="post">
                        <div class="modal-body">
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text" id="title" class="form-control" name="title">
                            </div>
                            <div class="form-group">
                                <label for="comment">Comment</label>
                                <textarea id="comment" class="form-control" name="content"></textarea>
                            </div>

                            <div class="form-group">
                                <input class="form-group-file" accept="image/*" name="post_image" type="file">
                            </div>
                            <div class="text-xs-centre">
                                <div id="reCaptcha" class="g-recaptcha" data-sitekey="6Lc0psUUAAAAAHbF17kNtEPOcTY_c90mgAHZjhWp"></div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close
                            </button>
                            <input type="submit" name="submit" class="btn btn-primary">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
