<nav id="pagination" aria-label="Page navigation example">
    <ul class="pagination justify-content-centre">
        <li class="page-item">
            <a class="page-link"
               href="posts.php?categoryID=<?php echo $view->currentCategory?>&page=<?php echo $view->previousPage?>&limit=<?php echo $view->limit?>&sort=<?php echo $view->sortBy?>&title=<?php echo $view->title?>">
                Previous
            </a>
        </li>

        <li class="page-item">
            <a class="page-link"
               href="posts.php?categoryID=<?php echo $view->currentCategory?>&page=<?php echo $view->previous2?>&limit=<?php echo $view->limit ?>&sort=<?php echo $view->sortBy?>&title=<?php echo $view->title?>">
                <?php echo $view->previous2?>
            </a>
        </li>

        <li class="page-item">
            <a class="page-link"
               href="posts.php?categoryID=<?php echo $view->currentCategory?>&page=<?php echo $view->previousPage?>&limit=<?php echo $view->limit?>&sort=<?php echo $view->sortBy?>&title=<?php echo $view->title?>">
                <?php echo $view->previousPage?>
            </a>
        </li>

        <li class="page-item active"><a class="page-link" href="#">
                <?php echo $view->currentPage ?>
            </a>
        </li>

        <li class="page-item">
            <a class="page-link"
               href="posts.php?categoryID=<?php echo $view->currentCategory?>&page=<?php echo $view->nextPage?>&limit=<?php echo $view->limit ?>&sort=<?php echo $view->sortBy?>&title=<?php echo $view->title?>">
                <?php echo $view->nextPage?>
            </a>
        </li>

        <li class="page-item">
            <a class="page-link"
               href="posts.php?categoryID=<?php echo $view->currentCategory?>&page=<?php echo $view->next2?>&limit=<?php echo $view->limit ?>&sort=<?php echo $view->sortBy?>&title=<?php echo $view->title?>">
                <?php echo $view->next2?>
            </a>
        </li>

        <li class="page-item">
            <a class="page-link"
               href="posts.php?categoryID=<?php echo $view->currentCategory?>&page=<?php echo $view->nextPage?>&limit=<?php echo $view->limit?>&sort=<?php echo $view->sortBy ?>&title=<?php echo $view->title?>">
                Next
            </a>
        </li>
    </ul>
</nav>