<form class="form-inline"
      action="posts.php?categoryID=<?php echo $view->currentCategory?>&page=1"
      method="POST">
    <div class="form-group">
        <label class="label">Post Title: </label>
        <input class="form-control" type="text" name="title">

        <label class="label"># of posts per page</label>
        <select class="form-control" name="limit">
            <option value="5">5</option>
            <option value="10">10</option>
            <option value="15">15</option>
            <option value="20">20</option>
            <option value="25">25</option>
        </select>

        <label>Sort By</label>
        <select class="form-control" name="sort">
            <option value="1">Newest First</option>
            <option value="2">Oldest First</option>
            <option value="3">Most Comments</option>
            <option value="4">Least Comments</option>
        </select>
    </div>

    <input class="btn btn-outline-primary" type="submit" name="submit">
</form>